apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-api-sm
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sentiment   # 👈 changed from sentiment-api
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
