version: "3.8"
services:
  sentiment:
    build: ./sentiment
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
  fraud:
    build: ./fraud
    ports:
      - "8001:8001"
    volumes:
      - ./models:/app/models
  rag:
    build: ./rag
    ports:
      - "8002:8002"
    volumes:
      - ./rag/index:/app/index
