apiVersion: v1
kind: Service
metadata:
  name: fraud-service
  namespace: default
  labels:
    app: fraud
spec:
  selector:
    app: fraud
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
